version: '3.8'

services:
  # 1. VERİTABANI (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    networks:
      - micro-network

  # 2. ZOOKEEPER (Kafka'nın çalışması için şart)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - micro-network

  # 3. KAFKA SUNUCUSU
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - micro-network

  # 4. EUREKA SERVER (Santral)
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-network

  # 5. ORDER SERVICE
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microservices_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network

  # 6. PAYMENT SERVICE
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microservices_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      # 🚀 BURASI KRİTİK: Alt çizgiler ve büyük harflerle Docker'a rotayı zorla öğretiyoruz
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network

  # 7. NOTIFICATION SERVICE
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - eureka-server
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge