apiVersion: v1
kind: Service
metadata:
  name: order-service # Diğer servisler beni bu isimle çağıracak
spec:
  selector:
    app: order-service # Hangi Pod'lara yönlendirme yapacağını seçer
  ports:
    - protocol: TCP
      port: 8081 # Dışarıdan gelecek port
      targetPort: 8081 # Pod'un içindeki port
  type: ClusterIP # Sadece K8s kümesi içinden erişim sağlar