server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    # 🚀 DEĞİŞTİ: Artık localhost değil, K8s'teki order-db servisine gidiyor!
    url: jdbc:postgresql://order-db:5432/payment_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 🚀 YENİ EKLENDİ: RedisIdempotencyService sınıfının çalışabilmesi için şart!
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    # 🚀 DEĞİŞTİ: Artık localhost değil, K8s'teki kafka servisine gidiyor!
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 🚀 SADECE BURASI DEĞİŞTİ VE ALTINDAKİ 'properties' KISMI SİLİNDİ:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/