apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:v3  # 🚀 VERSİYONU v3 YAPTIK
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://order-db:5432/payment_db
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            # 🚀 KAFKA'YA "SAKIN DOKUNMA, SADECE METİN VER" DİYORUZ
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              value: org.apache.kafka.common.serialization.StringDeserializer
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082